name: sunwise_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  another_flutter_splash_screen: 1.2.0
  google_fonts: ^5.1.0
  font_awesome_flutter: 10.7.0
  image_picker: ^1.1.2
  path: ^1.8.0
  image: 4.2.0
  flutter: 
    sdk: flutter
  http: ^1.2.1
  firebase_core: ^3.0.0
  firebase_database: ^11.0.1
  flutter_chat_ui: ^1.6.14
  lottie: ^3.1.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/sunwiselogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  uses-material-design: true

